"""Generate a YAML namespace map from extracted symbols."""

from pathlib import Path

from uncoded.extract import ModuleInfo
from uncoded.yaml_tree import render_yaml_tree

HEADER = """\
# Symbol index of this codebase, for agent navigation.
# Generated by uncoded — do not edit; regeneration overwrites.
#
# Pure key hierarchy (no lists, no values); indent to zoom in.
# Directory keys end with "/".
#
# For signatures and types, see stubs:
#   src/foo/bar.py  →  .uncoded/stubs/src/foo/bar.pyi
"""


def build_map(modules: list[ModuleInfo]) -> dict:
    """Build a nested dict representing the namespace.

    Keys are repo-relative paths. Directory keys have a trailing slash.
    Symbols sit directly under their file key.
    """
    root: dict = {}

    for module in modules:
        parts = Path(module.rel_path).parts
        current = root

        # Create intermediate directory entries
        for dir_part in parts[:-1]:
            key = dir_part + "/"
            if key not in current:
                current[key] = {}
            current = current[key]

        # Build the file entry — symbols directly under the file key.
        # Classes with methods map to their method list.
        # Classes without methods, bare functions, and constants map to None.
        file_entry: dict = {}

        for const in module.constants:
            file_entry[const] = None

        for cls in module.classes:
            members = cls.attributes + cls.methods
            file_entry[cls.name] = {m: None for m in members} if members else None

        for func in module.functions:
            file_entry[func] = None

        current[parts[-1]] = file_entry

    return root


def render_map(namespace: dict) -> str:
    """Render a namespace map dict as a YAML string with an explanatory header."""
    return render_yaml_tree(HEADER, namespace)
