# Generated by uncoded — do not edit; regeneration overwrites.
# tests/test_skill.py

from importlib.resources import files
from pathlib import Path
import uncoded.skill as skill_module
from uncoded.markers import GENERATED_MARKER
from uncoded.skill import SKILL_ROOTS, SKILLS, Skill, sync_skills

class TestSyncSkills:
    def test_skill_registry(self):
        ...

    def test_writes_skill_files(self, tmp_path):
        ...

    def test_creates_parent_directories(self, tmp_path):
        ...

    def test_content_has_frontmatter_and_body(self, tmp_path):
        ...

    def test_renderer_supplies_separator_for_body_without_leading_newline(self, monkeypatch):
        ...

    def test_content_has_provenance_marker(self, tmp_path):
        ...

    def test_returns_change_count_on_first_write(self, tmp_path):
        ...

    def test_returns_zero_when_already_in_sync(self, tmp_path):
        ...

    def test_idempotent(self, tmp_path):
        ...

    def test_check_mode_does_not_write(self, tmp_path):
        ...

    def test_check_mode_reports_change_when_missing(self, tmp_path):
        ...

    def test_check_mode_reports_no_change_when_in_sync(self, tmp_path):
        ...

    def test_removes_legacy_skill_files(self, tmp_path):
        ...

    def test_check_mode_reports_legacy_files_without_removing(self, tmp_path):
        ...

    def test_source_false_removes_existing_skill_files(self, tmp_path):
        ...

    def test_source_false_returns_zero_when_already_absent(self, tmp_path):
        ...

    def test_source_false_check_mode_reports_without_removing(self, tmp_path):
        ...

    def test_gate_unmet_removal_prunes_empty_directory(self, tmp_path):
        ...

    def test_legacy_removal_prunes_empty_directory(self, tmp_path):
        ...

    def test_pruning_skipped_when_directory_has_other_files(self, tmp_path):
        ...

    def test_docs_gate_builds_when_docs_true(self, tmp_path, monkeypatch):
        ...

    def test_docs_gate_skips_when_docs_false(self, tmp_path, monkeypatch):
        ...

    def test_no_legacy_names_skips_legacy_removal(self, tmp_path, monkeypatch):
        ...

    def test_code_navigation_written_when_source_set(self, tmp_path):
        ...

    def test_code_navigation_not_written_when_source_absent(self, tmp_path):
        ...

    def test_doc_navigation_written_when_docs_set(self, tmp_path):
        ...

    def test_doc_navigation_not_written_when_docs_absent(self, tmp_path):
        ...

    def test_doc_navigation_content_includes_orient_step(self, tmp_path):
        ...

class TestSyncSkillsProjectRootAnchor:
    def test_project_root_anchors_writes_independent_of_cwd(self, tmp_path, monkeypatch):
        ...

    def test_project_root_anchors_legacy_removal_independent_of_cwd(self, tmp_path, monkeypatch):
        ...
