# tests/test_docs_map.py

from pathlib import Path
import yaml
from uncoded.docs_map import DOCS_HEADER, build_docs_map, extract_headings, iter_doc_files, render_docs_map

class TestExtractHeadings:
    def test_empty_text(self):
        ...

    def test_h1_through_h6(self):
        ...

    def test_trailing_hashes_stripped(self):
        ...

    def test_trailing_hashes_with_surrounding_spaces_stripped(self):
        ...

    def test_trailing_hashes_multiple_stripped(self):
        ...

    def test_hash_attached_to_word_preserved(self):
        ...

    def test_multiple_hashes_attached_to_words_preserved(self):
        ...

    def test_hash_attached_to_word_with_closing_sequence(self):
        ...

    def test_seven_hashes_not_a_heading(self):
        ...

    def test_no_space_after_hash_not_a_heading(self):
        ...

    def test_hash_only_not_a_heading(self):
        ...

    def test_empty_title_not_a_heading(self):
        ...

    def test_setext_underline_equals_not_a_heading(self):
        ...

    def test_setext_underline_dashes_not_a_heading(self):
        ...

    def test_backtick_fence_suppresses_headings(self):
        ...

    def test_tilde_fence_suppresses_headings(self):
        ...

    def test_fence_with_info_string(self):
        ...

    def test_unclosed_fence_suppresses_rest_of_file(self):
        ...

    def test_tilde_does_not_close_backtick_fence(self):
        ...

    def test_backtick_does_not_close_tilde_fence(self):
        ...

    def test_preserves_order(self):
        ...

    def test_title_with_special_chars(self):
        ...

    def test_leading_spaces_not_a_heading(self):
        ...

class TestIterDocFiles:
    def test_single_file_root(self, tmp_path):
        ...

    def test_directory_walk_yields_md_files(self, tmp_path):
        ...

    def test_directory_walk_sorted(self, tmp_path):
        ...

    def test_directory_excludes_non_md(self, tmp_path):
        ...

    def test_directory_nested_subdir(self, tmp_path):
        ...

    def test_empty_directory_yields_nothing(self, tmp_path):
        ...

    def test_rel_path_is_relative_to_project_root(self, tmp_path):
        ...

    def test_skips_non_utf8_file_with_warning(self, tmp_path, capsys):
        ...

    def test_single_file_root_unreadable_yields_nothing(self, tmp_path, capsys):
        ...

    def test_bom_prefixed_file_heading_appears(self, tmp_path):
        ...

class TestBuildDocsMap:
    def test_empty_files(self):
        ...

    def test_headingless_file_maps_to_null(self, tmp_path):
        ...

    def test_single_heading(self):
        ...

    def test_nesting_parent_child(self):
        ...

    def test_level_skip_attaches_to_nearest_shallower(self):
        ...

    def test_heading_returns_to_same_level(self):
        ...

    def test_heading_not_starting_at_h1(self):
        ...

    def test_duplicate_sibling_disambiguation(self):
        ...

    def test_duplicate_increments_past_existing_suffix(self):
        ...

    def test_directory_structure_dir_key_has_trailing_slash(self):
        ...

    def test_two_files_in_same_directory(self):
        ...

    def test_multiple_files_flat(self):
        ...

class TestRenderDocsMap:
    def test_header_present(self):
        ...

    def test_yaml_parseable(self):
        ...

    def test_null_renders_clean(self):
        ...
