# tests/test_docs_map.py

from uncoded.docs_map import extract_headings

class TestExtractHeadings:
    def test_empty_text(self):
        ...

    def test_h1_through_h6(self):
        ...

    def test_trailing_hashes_stripped(self):
        ...

    def test_trailing_hashes_with_surrounding_spaces_stripped(self):
        ...

    def test_seven_hashes_not_a_heading(self):
        ...

    def test_no_space_after_hash_not_a_heading(self):
        ...

    def test_hash_only_not_a_heading(self):
        ...

    def test_empty_title_not_a_heading(self):
        ...

    def test_setext_underline_equals_not_a_heading(self):
        ...

    def test_setext_underline_dashes_not_a_heading(self):
        ...

    def test_backtick_fence_suppresses_headings(self):
        ...

    def test_tilde_fence_suppresses_headings(self):
        ...

    def test_fence_with_info_string(self):
        ...

    def test_unclosed_fence_suppresses_rest_of_file(self):
        ...

    def test_tilde_does_not_close_backtick_fence(self):
        ...

    def test_backtick_does_not_close_tilde_fence(self):
        ...

    def test_preserves_order(self):
        ...

    def test_title_with_special_chars(self):
        ...

    def test_leading_spaces_not_a_heading(self):
        ...
