# tests/test_stubs.py

import textwrap
import pytest
from uncoded.stubs import StubAssignment, StubClass, StubFunction, StubModule, StubParam, extract_stub, render_stub

class TestExtractStub:  # L16-321

    def test_simple_function(self):  # L17-31
        ...

    def test_function_no_annotations(self):  # L33-41
        ...

    def test_async_function(self):  # L43-51
        ...

    def test_private_function_included(self):  # L53-61
        ...

    def test_class_with_attributes_and_methods(self):  # L63-90
        ...

    def test_class_line_range(self):  # L92-108
        ...

    def test_class_with_bases(self):  # L110-116
        ...

    def test_class_no_bases(self):  # L118-124
        ...

    def test_docstring_first_sentence_only(self):  # L126-133
        ...

    def test_no_docstring(self):  # L135-141
        ...

    def test_kwargs_and_varargs(self):  # L143-151
        ...

    def test_imports_collected(self):  # L153-167
        ...

    def test_syntax_error_raises(self):  # L169-171
        ...

    def test_source_order_preserved(self):  # L173-182
        ...

    def test_constant_annotated_with_value(self):  # L184-194
        ...

    def test_constant_unannotated_with_value(self):  # L196-204
        ...

    def test_constant_bare_annotation(self):  # L206-213
        ...

    def test_constant_value_too_long_elided(self):  # L215-221
        ...

    def test_constant_private_included(self):  # L223-228
        ...

    def test_type_alias_classic(self):  # L230-240
        ...

    def test_type_alias_pep695(self):  # L242-250
        ...

    def test_tuple_unpacking_skipped(self):  # L252-257
        ...

    def test_class_with_unannotated_attribute(self):  # L259-271
        ...

    def test_property_rendered_as_attribute(self):  # L274-289
        ...

    def test_property_without_return_annotation(self):  # L291-301
        ...

    def test_property_setter_and_deleter_suppressed(self):  # L303-321
        ...

class TestRenderStub:  # L324-547

    def test_header_contains_path(self):  # L325-327
        ...

    def test_imports_rendered(self):  # L329-335
        ...

    def test_function_line_range(self):  # L337-343
        ...

    def test_async_function_prefix(self):  # L345-352
        ...

    def test_function_with_annotations(self):  # L354-367
        ...

    def test_docstring_excerpt_rendered(self):  # L369-383
        ...

    def test_class_with_bases(self):  # L385-390
        ...

    def test_class_single_line_range(self):  # L392-397
        ...

    def test_function_single_line_range(self):  # L399-404
        ...

    def test_class_no_bases(self):  # L406-411
        ...

    def test_attribute_with_annotation(self):  # L413-425
        ...

    def test_method_indented(self):  # L427-447
        ...

    def test_ends_with_newline(self):  # L449-451
        ...

    def test_property_rendered_as_class_attribute(self):  # L453-467
        ...

    def test_constant_with_value_rendered(self):  # L469-478
        ...

    def test_constant_annotated_with_value_rendered(self):  # L480-493
        ...

    def test_constant_elided_rendered(self):  # L495-504
        ...

    def test_constant_bare_annotation_rendered(self):  # L506-515
        ...

    def test_type_alias_pep695_rendered(self):  # L517-530
        ...

    def test_unannotated_class_attribute_rendered(self):  # L532-547
        ...
