# Generated by uncoded — do not edit; regeneration overwrites.
# src/uncoded/config.py

import tomllib
from dataclasses import dataclass
from pathlib import Path

def find_pyproject_toml(start: Path) -> Path | None:
    ...

def _has_uncoded_section(*, pyproject_path: Path) -> bool:
    ...

def _find_config_file(*, start: Path) -> Path | None:
    ...

def read_config(start: Path) -> Config | None:
    ...

class ConfigError(Exception):
    ...

class Config:
    project_root: Path
    source_roots: list[Path]
    doc_roots: list[Path]
