# Generated by uncoded — do not edit; regeneration overwrites.
# src/uncoded/markers.py

GENERATED_MARKER = 'Generated by uncoded — do not edit; regeneration overwrites.'
INDEX_GITIGNORE_CONTENT = f'# {GENERATED_MARKER}\n*\n'
