# src/uncoded/skill.py

from pathlib import Path
from uncoded.sync import remove_file, sync_file

SKILL_OUTPUTS = ...
LEGACY_SKILL_OUTPUTS = ...
_SKILL_CONTENT = ...

def sync_skill(*, project_root: Path, check: bool) -> bool:
    ...
