# src/uncoded/skill.py

from pathlib import Path
from uncoded.sync import remove_file, sync_file

SKILL_OUTPUTS = ...
LEGACY_SKILL_OUTPUTS = ...
_SKILL_CONTENT = ...

def sync_skill(*, check: bool) -> bool:
    """Write the coherence-review skill file to all supported agent locations."""
    ...
