# Generated by uncoded — do not edit; regeneration overwrites.
# src/uncoded/yaml_tree.py

import yaml

def render_yaml_tree(header: str, mapping: dict) -> str:
    ...

class _CleanDumper(yaml.SafeDumper):
    def increase_indent(self, flow: bool, indentless: bool) -> None:
        ...
